### ISSUE TITLE
Anonymous customer bug on SagePay direct integration

### ISSUE THREAD

**Issue by chrisdaaaaay** [BluefinDigital/Merchello.Plugins.SagePay#11]
Hi Barry, Chris, et al :) Thank you very much for making this plugin available...

I think I found a bug with the latest version of Merchello and have submitted a pull request to fix it.

To replicate the bug. Proceed to checkout as an anonymous customer, use SagePay direct, and enter card details on the SagePay pages.

The redirection to receipt will fail and show a null reference error message.

This is for the check against invoice.CustomerKey, which isn't required to successfully mark the order as paid (and isn't used in the code that follows).

Running Merchello 1.13.2 on Umbraco 7.3.4.

**Comment by BarryFogarty** [comment]
Thank you for your contribution Chris.  I did not need anonymous customers or SagePay direct in my integration project so I never had the opportunity to test the plugin under these conditions.  You code looks fine through and I have merged the PR - thanks again.
