### ISSUE TITLE
Provider settings

### ISSUE THREAD

**Issue by BarryFogarty** [BluefinDigital/Merchello.Plugins.SagePay#4]
I don't have any experience with the server and direct integration methods - so do the Gateway provider settings cover what is needed?  If not, the best approach would be to split out the specific settings into payment METHOD configs and manage them from their own side panel dialogs.  What do you think?

**Comment by chris64digital** [comment]
That sounds like a good idea. I believe that the LiveMode setting will be used by all the sagepay integrations but ReturnUrl and EncryptionPassword are not used by direct.
