### ISSUE TITLE
The Live/Test setting does not appear to work

### ISSUE THREAD

**Issue by chris64digital** [BluefinDigital/Merchello.Plugins.SagePay#5]
I have just been attempting to test my sagepay integration and found that the live/test environment setting does not appear to work. I believe that the SagePayProcessorSettings object is looking for a bool (LiveMode) and the angular page is providing a string (Environment). If you can confirm this to be the case I will create a pull request to use the Environment variable and remove the LiveMode variable.

**Comment by BarryFogarty** [comment]
Hi Chris,

I have a psuedo property to deal with this in SagePayProcessorSettings:

public bool LiveMode
            {
                get
                {
                    return this.Environment.ToLowerInvariant() == "live";
                }
            }
