### ISSUE TITLE
What version of SagePay

### ISSUE THREAD

**Issue by gordonsaxby** [BluefinDigital/Merchello.Plugins.SagePay#7]
Sorry if this is the wrong place to ask, but I can't find another.

What version of Form Integration does this plugin support? SagePay are pushing for clients to move onto v3 by the end of July, I believe, so I need to know if this is suitable or can be easily made compatible.

**Comment by BarryFogarty** [comment]
Hi Gordon,

Yes this supports v3.00 of form integration.  It does not support any earlier version.
