### ISSUE TITLE
Gateway Provider setup not working

### ISSUE THREAD

**Issue by gordonsaxby** [BluefinDigital/Merchello.Plugins.SagePay#8]
I followed the instructions here our.umbraco.org/projects/collaboration/merchello/merchello/60931-SagePay-payment-provider#comment-209638 and the gateway has appeared but does not seem to be configured properly.

The text {{dialogData.provider.name}} appears at the top of the settings window and the button at the bottom (Save?) has no text and does not save the settings.

I am using Merchello 1.9

**Comment by BarryFogarty** [comment]
Sounds like an angular issue - I am in the process of upgrading my clients site to 1.9 which may involve an update to this plugin.  I will test and let you know here if so.

Do you have any errors in the console?

**Comment by gordonsaxby** [comment]
No error messages that I can see - just a small blob where the OK (?) button should be, and nothing where the cancel (?) button should be.

As it is, I cannot save the settings and therefore cannot use the plugin.
